epgctl/debug.o: epgctl/debug.c epgctl/mytypes.h epgctl/debug.h
epgctl/epgacqctl.o: epgctl/epgacqctl.c epgctl/mytypes.h epgctl/debug.h \
 epgvbi/btdrv.h /usr/include/linux/videodev.h epgvbi/ttxdecode.h \
 epgdb/epgblock.h epgdb/epgdbif.h epgdb/epgstream.h epgdb/epgqueue.h \
 epgdb/epgtscqueue.h epgdb/epgdbsav.h epgdb/epgdbmgmt.h \
 epgdb/epgdbmerge.h epgui/uictrl.h epgui/epgmain.h \
 epgctl/epgctxmerge.h epgctl/epgctxctl.h epgctl/epgscan.h \
 epgctl/epgacqctl.h epgctl/epgacqsrv.h epgdb/epgnetio.h \
 epgctl/epgacqclnt.h
epgctl/epgscan.o: epgctl/epgscan.c epgctl/mytypes.h epgctl/debug.h \
 epgvbi/cni_tables.h epgvbi/vbidecode.h epgvbi/tvchan.h epgvbi/btdrv.h \
 /usr/include/linux/videodev.h epgvbi/ttxdecode.h epgdb/epgblock.h \
 epgdb/epgdbif.h epgdb/epgdbsav.h epgdb/epgstream.h epgdb/epgqueue.h \
 epgdb/epgdbmgmt.h epgui/uictrl.h epgctl/epgctxctl.h \
 epgctl/epgacqctl.h epgctl/epgscan.h
epgctl/epgctxctl.o: epgctl/epgctxctl.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgdbif.h epgdb/epgdbsav.h epgdb/epgdbmgmt.h \
 epgui/uictrl.h epgui/epgmain.h epgctl/epgctxmerge.h \
 epgctl/epgctxctl.h
epgctl/epgctxmerge.o: epgctl/epgctxmerge.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgui/epgmain.h epgui/uictrl.h epgctl/epgctxctl.h \
 epgdb/epgdbif.h epgdb/epgtscqueue.h epgdb/epgdbsav.h \
 epgdb/epgdbmgmt.h epgdb/epgdbmerge.h epgctl/epgacqctl.h \
 epgctl/epgctxmerge.h
epgctl/epgacqclnt.o: epgctl/epgacqclnt.c epgctl/mytypes.h epgctl/debug.h \
 epgctl/epgversion.h epgdb/epgblock.h epgdb/epgswap.h epgdb/epgdbif.h \
 epgdb/epgqueue.h epgdb/epgtscqueue.h epgdb/epgnetio.h \
 epgdb/epgdbmerge.h epgui/epgmain.h epgui/epgtxtdump.h epgui/uictrl.h \
 epgctl/epgacqctl.h epgctl/epgctxctl.h epgctl/epgacqsrv.h \
 epgdb/epgdbsav.h epgctl/epgacqclnt.h
epgctl/epgacqsrv.o: epgctl/epgacqsrv.c epgctl/mytypes.h epgctl/debug.h \
 epgctl/epgversion.h epgdb/epgblock.h epgdb/epgswap.h epgdb/epgqueue.h \
 epgdb/epgtscqueue.h epgdb/epgdbmgmt.h epgdb/epgdbmerge.h \
 epgdb/epgdbsav.h epgdb/epgnetio.h epgui/uictrl.h epgctl/epgacqctl.h \
 epgctl/epgacqsrv.h epgctl/epgctxctl.h
epgdb/epgstream.o: epgdb/epgstream.c epgctl/mytypes.h epgctl/debug.h \
 epgvbi/btdrv.h /usr/include/linux/videodev.h epgvbi/ttxdecode.h \
 epgvbi/hamming.h epgdb/epgblock.h epgui/epgtxtdump.h epgdb/epgqueue.h \
 epgdb/epgstream.h
epgdb/epgdbmerge.o: epgdb/epgdbmerge.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgui/epgmain.h epgdb/epgdbmgmt.h \
 epgdb/epgtscqueue.h epgdb/epgstream.h epgui/pilistbox.h \
 epgdb/epgdbmerge.h
epgdb/epgdbsav.o: epgdb/epgdbsav.c epgctl/mytypes.h epgctl/epgversion.h \
 epgctl/debug.h epgdb/epgblock.h epgdb/epgswap.h epgdb/epgdbmgmt.h \
 epgdb/epgdbfil.h epgdb/epgdbif.h epgdb/epgdbsav.h
epgdb/epgdbmgmt.o: epgdb/epgdbmgmt.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgui/pilistbox.h epgdb/epgqueue.h \
 epgdb/epgtscqueue.h epgdb/epgdbmgmt.h epgctl/epgctxmerge.h \
 epgctl/epgacqsrv.h epgdb/epgnetio.h epgdb/epgdbmerge.h \
 epgdb/epgdbsav.h epgctl/epgctxctl.h epgctl/epgacqctl.h
epgdb/epgdbif.o: epgdb/epgdbif.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgdbfil.h epgdb/epgdbif.h epgdb/epgdbmgmt.h \
 epgdb/epgstream.h
epgdb/epgdbfil.o: epgdb/epgdbfil.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgstream.h epgdb/epgdbfil.h epgdb/epgdbif.h
epgdb/epgblock.o: epgdb/epgblock.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgswap.h
epgdb/epgnetio.o: epgdb/epgnetio.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgqueue.h epgdb/epgtscqueue.h \
 epgdb/epgdbmgmt.h epgdb/epgdbmerge.h epgdb/epgdbsav.h \
 epgdb/epgnetio.h
epgdb/epgqueue.o: epgdb/epgqueue.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgqueue.h
epgdb/epgtscqueue.o: epgdb/epgtscqueue.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgstream.h epgdb/epgdbfil.h epgdb/epgdbif.h \
 epgdb/epgtscqueue.h
epgui/uictrl.o: epgui/uictrl.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgdbfil.h epgdb/epgdbif.h epgdb/epgdbsav.h \
 epgctl/epgctxmerge.h epgctl/epgacqctl.h epgctl/epgscan.h \
 epgctl/epgacqsrv.h epgdb/epgnetio.h epgdb/epgtscqueue.h \
 epgdb/epgdbmerge.h epgctl/epgctxctl.h epgctl/epgacqclnt.h \
 epgui/epgmain.h epgui/pifilter.h epgui/pilistbox.h epgui/pioutput.h \
 epgui/uictrl.h epgui/menucmd.h epgui/statswin.h epgui/timescale.h
epgui/pilistbox.o: epgui/pilistbox.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgdbfil.h epgdb/epgdbif.h epgctl/epgacqctl.h \
 epgui/epgmain.h epgui/uictrl.h epgctl/epgctxctl.h epgui/pifilter.h \
 epgui/pioutput.h epgui/pilistbox.h
epgui/pioutput.o: epgui/pioutput.c epgctl/mytypes.h epgctl/debug.h \
 epgctl/epgversion.h epgdb/epgblock.h epgdb/epgdbfil.h epgdb/epgdbif.h \
 epgdb/epgtscqueue.h epgdb/epgdbmerge.h epgui/epgmain.h \
 epgui/pdc_themes.h epgui/pifilter.h epgui/pilistbox.h \
 epgui/pioutput.h epgvbi/btdrv.h /usr/include/linux/videodev.h \
 epgvbi/winshm.h epgvbi/winshmsrv.h
epgui/pifilter.o: epgui/pifilter.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgdbfil.h epgdb/epgdbif.h epgui/epgmain.h \
 epgui/pdc_themes.h epgui/pilistbox.h epgui/pioutput.h \
 epgui/pifilter.h epgui/uictrl.h
epgui/statswin.o: epgui/statswin.c epgctl/mytypes.h epgctl/debug.h \
 epgvbi/ttxdecode.h epgdb/epgblock.h epgdb/epgdbfil.h epgdb/epgdbif.h \
 epgctl/epgacqctl.h epgctl/epgscan.h epgctl/epgctxmerge.h \
 epgctl/epgacqclnt.h epgdb/epgnetio.h epgdb/epgtscqueue.h \
 epgdb/epgdbmerge.h epgui/epgmain.h epgui/uictrl.h epgui/statswin.h
epgui/timescale.o: epgui/timescale.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgdbfil.h epgdb/epgdbif.h epgdb/epgtscqueue.h \
 epgctl/epgacqctl.h epgctl/epgctxmerge.h epgui/epgmain.h \
 epgui/uictrl.h epgui/timescale.h
epgui/pdc_themes.o: epgui/pdc_themes.c epgctl/mytypes.h epgctl/debug.h \
 epgui/pdc_themes.h
epgui/menucmd.o: epgui/menucmd.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgdbmgmt.h epgdb/epgdbfil.h epgdb/epgdbif.h \
 epgdb/epgtscqueue.h epgdb/epgdbmerge.h epgdb/epgnetio.h \
 epgctl/epgacqsrv.h epgdb/epgdbsav.h epgctl/epgctxctl.h \
 epgctl/epgacqctl.h epgctl/epgacqclnt.h epgctl/epgscan.h \
 epgctl/epgctxmerge.h epgui/epgmain.h epgui/epgtxtdump.h \
 epgui/epgtabdump.h epgui/pilistbox.h epgui/pioutput.h \
 epgui/pifilter.h epgui/pdc_themes.h epgui/menucmd.h epgui/uictrl.h \
 epgui/xawtv.h epgui/wintvcfg.h epgvbi/vbidecode.h epgvbi/cni_tables.h \
 epgvbi/tvchan.h epgvbi/btdrv.h /usr/include/linux/videodev.h
epgui/epgmain.o: epgui/epgmain.c epgctl/mytypes.h epgctl/epgversion.h \
 epgctl/debug.h epgdb/epgblock.h epgdb/epgdbfil.h epgdb/epgdbif.h \
 epgdb/epgdbmgmt.h epgdb/epgdbsav.h epgdb/epgnetio.h \
 epgdb/epgtscqueue.h epgdb/epgdbmerge.h epgctl/epgacqctl.h \
 epgctl/epgscan.h epgctl/epgacqsrv.h epgctl/epgctxctl.h \
 epgctl/epgacqclnt.h epgui/uictrl.h epgui/statswin.h epgui/timescale.h \
 epgui/menucmd.h epgui/pilistbox.h epgui/pioutput.h epgui/pifilter.h \
 epgui/xawtv.h epgui/wintv.h epgui/wintvcfg.h epgui/epgtabdump.h \
 epgui/nxtv_logo.xbm epgui/ptr_up.xbm epgui/ptr_down.xbm \
 epgui/pan_updown.xbm epgui/qmark.xbm epgui/zoom_in.xbm \
 epgui/zoom_out.xbm epgvbi/btdrv.h /usr/include/linux/videodev.h \
 epgvbi/winshmsrv.h epgui/epgmain.h
epgui/xawtv.o: epgui/xawtv.c epgctl/mytypes.h epgctl/debug.h epgvbi/tvchan.h \
 epgvbi/btdrv.h /usr/include/linux/videodev.h epgvbi/ttxdecode.h \
 epgdb/epgblock.h epgdb/epgdbfil.h epgdb/epgdbif.h epgctl/epgacqctl.h \
 epgui/epgmain.h epgui/pilistbox.h epgui/xawtv.h
epgui/epgtxtdump.o: epgui/epgtxtdump.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgdbfil.h epgdb/epgdbif.h epgui/epgtxtdump.h \
 epgui/pdc_themes.h
epgui/epgtabdump.o: epgui/epgtabdump.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgdb/epgdbfil.h epgdb/epgdbif.h epgctl/epgctxctl.h \
 epgui/pdc_themes.h epgui/epgmain.h epgui/uictrl.h epgui/menucmd.h \
 epgui/pioutput.h epgui/epgtabdump.h
epgvbi/btdrv4linux.o: epgvbi/btdrv4linux.c epgctl/mytypes.h epgctl/debug.h \
 epgvbi/vbidecode.h epgvbi/btdrv.h /usr/include/linux/videodev.h
epgvbi/vbidecode.o: epgvbi/vbidecode.c epgctl/mytypes.h epgctl/debug.h \
 epgdb/epgblock.h epgvbi/ttxdecode.h epgvbi/hamming.h \
 epgvbi/vbidecode.h
epgvbi/ttxdecode.o: epgvbi/ttxdecode.c epgctl/mytypes.h epgctl/debug.h \
 epgvbi/cni_tables.h epgvbi/hamming.h epgvbi/btdrv.h \
 /usr/include/linux/videodev.h epgvbi/ttxdecode.h
epgvbi/hamming.o: epgvbi/hamming.c epgctl/mytypes.h epgctl/debug.h \
 epgvbi/hamming.h
epgvbi/tvchan.o: epgvbi/tvchan.c epgctl/mytypes.h epgctl/debug.h \
 epgvbi/btdrv.h /usr/include/linux/videodev.h epgvbi/tvchan.h
epgvbi/cni_tables.o: epgvbi/cni_tables.c epgctl/mytypes.h epgctl/debug.h \
 epgvbi/cni_tables.h
