# ---------------------------------------------------------------------------
#
#  Nextview decoder online manual
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License Version 2 as
#  published by the Free Software Foundation. You find a copy of this
#  license in the file COPYRIGHT in the root directory of this release.
#
#  THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
#  BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
#  MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#
#  Description:
#
#    User's documentation in Perl "POD" format. The content is
#    converted into various other formats by use of different scripts:
#    UNIX manpage by pod2man; HTML web page by pod2html (needs manual
#    adjustments) and the online help by a self-made script. The releases
#    should contain the converted files, so that the user is not forced
#    to install Perl.
#
#  Author: Tom Zoerner
#
# $Id: nxtvepg.pod,v 1.45 2001/06/05 19:01:51 tom Exp tom $
# ---------------------------------------------------------------------------

=head1 NAME

nxtvepg - Decoder, Browser and Analyzer for the Nextview Electronic Programme Guide

=for html
<TITLE>Nextview EPG Decoder Documentation</TITLE>
<LINK href="nxtvepg.css" rel=stylesheet type=text/css>
<META http-equiv="Content-Type" content="text/html; charset=iso8859-1">
<META name="language" content="en">
<META name="author" content="Tom Zoerner">
<META name="copyright" content="Tom Zoerner">
<META name="keywords" content="nexTView,nxtvepg,TV schedule,Linux,software download,bttv,video4linux,VBI,vertical blanking interval,multimedia,data service,subscription free,TV tuner card,Bt848,Booktree,video capture,decoder,browser,EPG,teletext,Bt878,electronic program guide,TV-Guide,TV program listing">
<META name="description" content="Online Documentation for the nxtvepg software, which offers access to a subscription-free electronic TV program guide. Nextview currently is broadcasted in Germany, Austria, Switzerland, and France and covers the schedules of all major TV networks in these countries.">
<META name="robots" content="index, follow">
<META name="revisit-after" content="01 month">
</HEAD>
<BODY BGCOLOR=#f8f8f8>
<P><HR><P>
<H1>Nextview EPG Decoder Documentation</H1>
This is the manual page for the
<A HREF="http://nxtvepg.tripod.com/">nxtvepg</A> software package.

=head1 SYNOPSIS

B<nxtvepg> S<[ options ]> S<[ database ]>

=head1 DESCRIPTION

B<nxtvepg>
is an X11 and Win32API application to decode, analyze and browse TV programme
schedules transmitted on analog TV channels as defined in ETS 300 707:
"Protocol for a TV Guide using electronic data transmission" by the
European Telecommunications Standards Institute.

The Nextview standard was developed for use in TV sets, but it can also be
received and used in a PC - provided you have a Teletext capable TV tuner
card and are lucky enough to have a Nextview content provider in your country.

B<nxtvepg>
enables you to obtain free TV programme listings for all of the major
networks in Germany, Austria, France and Switzerland. Currently
Nextview EPG is transmitted by the following TV networks (note that each
of these EPGs cover not only the provider's programme but also that of
many other networks):

=over 4

=item *

In Germany and Austria: Pro7, 3Sat, RTL-II.

=item *

In Switzerland: EuroNews, TSR1 and others.

=item *

In France: Canal+, M6, TV5.

=back

For up-to-date information check the nxtvepg homepage in the Internet
(see the About popup in the Help menu). If you don't receive any of the
channels listed above, you can only use the demo mode as described
with the B<-demo> command line option.

=head1 OPTIONS

Summary of command line options:

=over 4

=item B<-display> I<display>

UNIX only: The display on which the windows will be created.
Default: taken from environment variable DISPLAY.

=item B<-geometry> I<geometry>

Specifies the position of the main window, e.g.  B<-geometry -0+0>
to put the main window in the upper right corner of the visible screen.
The size of the window cannot be changed.

=item B<-iconic>

Start with the main window iconified (i.e. minimized).

=item B<-rcfile> I<path>

Specify an alternate configuration file.
Default: on UNIX ~/.nxtvepgrc,
on Windows nxtvepg.ini in the current directory.

=item B<-dbdir> I<directory>

Specify an alternate directory for the databases.
Default: On UNIX /usr/tmp/nxtvdb, on Windows the current directory.
Note that the database management is not equipped for concurrent writing,
so if you have more than one TV tuner card in your system or network,
relocate the directory into the users' homes.

=item B<-card> I<index>

Specify which tuner card to use, if you have more than one.
The given index is appended to /dev/vbi and /dev/video.
Default: index 0, i.e. the card in the first PCI slot.

=item B<-provider> I<CNI>

Select a provider by its hexadecimal CNI (Country and Network Identifier),
e.g. C<-provider d94> for "Pro Sieben". You can find out the provider's CNI
during a provider scan or from the database file names.
Default: the last provider selected during the previous session.

=item B<-noacq>

Start with acquisition disabled.
The acquisition can still be started later from the Control menu.

=item B<-demo> I<path>

Load database given by I<path>
and enter demo mode. In this mode all entries of the database are shifted
into the presence, i.e. just far enough so that none expire. Hence the
entries' dates and times are not for real and acquisition or database
reselection is not possible.

=item B<-help>

List all available command line options.

=back

After the options you can add a database filename. This is equivalent
to specifying B<-dbdir> and B<-provider>. The provider CNI is taken
from the file name. If the file name does not have the format as
defined in L<"FILES">, it's assumed to be a demo database and loaded
just as with the B<-demo> option. The database filename argument
silently overrides any previously given options.

This is particularily useful for users of graphical file managers
(like the Windows Explorer) who can just drag and drop a database file
onto the executable. When used on Windows systems the working
directory is set to the one that contains the executable, because
the Explorer seems to set it to the user's desktop root, so that none
of the DLLs and drivers are found.

Note to Windows users: all these options - unless otherwise noted -
are available in the Win32 version too. You can supply the options
either from a "MS-DOS" command prompt or batch file, or by appending
them to the executable in a shortcut definition.



=head1 GETTING STARTED

Before you can start reading in TV programme schedules (called
I<acquisition>
from here on), you have to do just a few configurations. Which
ones depends on your setup and will be described in the following.
As long as your browser window contains no data, there's also a
recommondation how to get to data in the browser window,
highlighted with a yellow background.

This manual describes all features of nxtvepg in detail. You
do not have to read all of it at once to operate the software.
However it's recommended to skim at least through L<"BASIC BROWSING">,
L<"DATA ACQUISITION"> and L<"FILTERING">.

Windows users first have to configure the driver for their TV card.
Therefore invoke the 'TV card input' dialog from the Configure menu
(see L<"CONFIGURATION">) and specify the type of your tuner. In Germany,
Austria and Switzerland it should be either Philips PAL or Temic PAL.
In France it's one of the SECAM types. Then select how your card's I<PLL>
needs to be set up. On most cards it's either I<No init> or I<28 MHz>.
If you're not sure about your configuration, start with the topmost and
then try them one after each other and start an EPG scan inbetween to
check if the tuner works. If this seems too much work, open your PC
and read the manufacturer from the metal tuner box on the TV tuner card.

If you don't have an antenna connected to your PC, you can select an
external source for video input. If you have problems see F<README>
for more details and a list of error messages from the Windows driver.

UNIX users just need to check if the correct input source and
frequency table are selected in the TV card input dialog.

In the next step - if you chose to use the TV tuner - run a provider
scan from the Configure menu.  During the scan all TV channels are
checked for Nextview transmissions. After the scan has finished,
open the provider selection dialog from the Configure menu and select
you favorite one.

If the provider scan does not find all Nextview provider channels
(possibly due to weak reception - this is a very simple scan that does
not attempt any fine-tuning) check the I<Slow> button and try again.
If this does not help, you can still add the missing providers manually.
set the acquisition mode to I<external> or I<passive> (UNIX only). Then
use an external application to tune the channel (Windows users have to
stop acquisition first; then start the TV application; then tune the
channel; then quit the other application; finally start acquisition again).
In external mode nxtvepg will not touch the tuner and wait infinitly for
Nextview reception on the current channel.  On Windows (and Linux with
bttv drivers version 0.7.50 and earlier) this method has the disadvantage
that no frequency will be known for this provider so this procedure has
to be repeated every time you start acquisition.

Alternatively if you decided not to use the tuner, open the Acquisition
mode dialog from the Configure menu and select external mode. Then provide
the video signal of one of the content provider channels listed in the
introduction to the selected input socket. As soon as an EPG provider is
recognized, its data will appear in the browser window.
See L<"DATA ACQUISITION"> about the disadvantages of not using the
TV tuner as input.

Acquisition of a complete database takes about 20 minutes. However
programmes that are nearer in the future are available much faster,
since they are transmitted more often. The currently running and
directly following programmes of all networks are usually available
after about 2-3 minutes max.



=head1 BASIC BROWSING

The browser mainly consists of two windows: the upper one contains
a list of programme titles, sorted by start time. All currently running
programmes (or rather: all programmes that should be running according
to their start time) are marked by a light blue background color.
One line in the list is selected by a cursor; the lower window contains
the attributes and description for this selected title. The amount of
information available here depends entirely on the content provider.

The basic browsing of programme information works very straight-forward.
You can either use the mouse or the keyboard cursor keys:

With the mouse, you can click on any title to select it and display its
description in the lower window. With a double-click you open a popup
window with a summary of all attributes known for that title.  See
L<"FILTERING"> on how to use those for filtering. Use the scrollbar
to scroll the listing forward to programmes farer in the future.

With the keyboard, use the Cursor up/down keys to select any title.
For fast scrolling use the page up/down keys. With the Home key you
always get back to the first title. With TAB and SHIFT-TAB you can
move the keyboard input focus to other widgets, e.g. to the scrollbars
or the shortcut list. On Unix, the menus can be accessed with the
Meta key (usually the ALT key) together with one of the underlined
characters in the menu buttons.

nxtvepg can communicate with the I<xawtv> TV application (UNIX only)
to provide a connection in both directions: Firstly you'll find a
I<Tune-TV> button in the main window below the clock. When you press it,
the network of the currently selected programme will be tuned into xawtv.
With the right mouse button you can also pop up a small menu which offers
basic control over xawtv. Secondly, when you change the channel in xawtv,
the cursor will automatically jump onto the programme currently running
on that network. To use these features, you'll have to open the
I<Network name configuration> dialog at least once to synchronize
network names with your xawtv station names. See L<"CONFIGURATION"> for
details.

At the bottom of the window there is a status line which informs you
about the state of the browser database and background acquisition.
It's basically a very dense summary of the B<Statistics> popups from
the B<Control> menu and is especially useful to warn you about the
database age or stalled acquisition.

I<Note:>
For most providers it holds true that descriptions are available only
(or only in full length) for currently running programmes and those
whose start time is very close. This time span for full coverage can
be as short as 2 hours, or 3 titles per network. For details on the
acquisition process see the following chapter.



=head1 DATA ACQUISITION

As long as acquisition is enabled, programme titles are constantly being
acquired or updated in the background. You will notice that all incoming
programme information is instantly inserted to the programme listing.
Every effort is taken to not alter the cursor position or title selection,
except if the cursor is on the very first item - then the cursor
stays on top.

By default, the acquisition always works for the provider whose database
you have loaded into the browser. Therefore, upon program start or whenever
you switch providers, the TV tuner is set onto the frequency of the
provider's TV channel.  Please note that this mode is only possible after
a provider scan, because that's the only way to find out the frequencies.
Check out L<"ACQUISITION MODES"> for more sophisticated acquisition
strategies.

If you do not choose the TV tuner as input (e.g. if you choose an external
source via the Composite or S-Video input sockets), or if the TV tuner is
kept busy by another application (UNIX only, e.g. if you watch TV) data is
still being acquired, but it's no longer possible to automatically change
the TV channel. Hence you are resposible for selecting the channel of the
provider who's database you want to load or refresh. If a transmission
belonging to a different provider than the one selected in the browser
is detected, a second database is automatically opened in the background
to store the incoming data.

The transmitted database is constantly in change: Elapsed titles are
removed, new titles appended, and the titles closest to the current time
updated with an increased amount of description. (The reason that the
complete description is not transmitted for all titles is simply that
the size of the database has to be reduced - it shall be transmitted
in 20 minutes maximum.)  So you should start the acquisition as often
as possible, about every 2-3 hours, at least a couple of minutes before
you browse.

You can monitor the progress of acquisition with the timescale and
database statistics windows from the Control menu. See L<"STATISTICS">
for details.



=head1 ACQUISITION MODES

The acquisition mode configuration dialog enables you to control for which providers
data is collected, and in which order. It's mainly intended for users who use
more than one provider's database, i.e. in a merged database, or want to
optimize startup time. If you're happy with a single provider or don't
want to browse immediately after program start, you should keep the
default, which is loading data always for the provider selected in the
browser.

=over 4

=item B<Passive>

UNIX only:
In this mode the software never accesses the video device and never changes
the input channel or tuner frequency.  It's useful if you want to set up the
source with command line tools like I<v4lctl>. If you're using applications
which keep the video device busy (e.g. a TV application) you don't need this
mode, because when nxtvepg detects an unsolicited channel change, it
automatically switches to the passive mode for as long as the video device
remains busy.

Please note: when nxtvepg does not control the input channel, it can not
automatically take care of updating your databases. Even if the browser
database should be completely empty, no data will appear until you tune in
the provider's channel manually with an external application. Because of
this, passive mode is depreciated.

=item B<External>

This is the recommended mode for Composite or S-Video input sources. Only
the input source will be set; the tuner is not touched. Hence the provider
channel has to be selected either externally (e.g. in a satellite receiver
connected to the Composite or S-Video input sockets) or by a different
application (e.g. TV application, UNIX only), just like in passive mode.

On Windows systems this mode can be used if your tuner is not known to
nxtvepg, i.e. if the EPG scan does not find any channels with all of the
available tuner types. In this case tune in the provider channel with a
TV application; then quit this application and start nxtvepg. When you
view the acquisition statistics from the Control menu, the VPS/PDC code
of the tuned channel should appear in the lower half of the window.

=item B<Follow-UI>

This is the default mode: the acquisition always works for the provider you
have selected for the browser (i.e. user interface). If you change the
provider in the browser window, acquisition follows by tuning the new channel.
Of course this requires to have performed an EPG scan at least once, so that
the tuner frequencies of all providers are known. When you use a merged
database in the browser, acquisition works on each of the merged providers,
one after another, just like in the mode described next.

=item B<Manually selected>

This mode enables you to manually select for which providers the acquisition
should work. If you select more than one provider, they are loaded one after
another, in your specified order. Warning: if you choose a provider for the
browser that's not on the list, no data will be loaded into the browser,
even if it's completely empty.

Since transmission errors have to be considered, it's not attempted
to load every single block of a provider before acquisitions switches to the
next. Instead a statistical criterium was defined, that regards the variance
in coverage of all networks contained in the database, and the slope of that
variance.

=item B<Cyclic: Now - Near - All>

Like the previous mode, this one enables you to specify a list of providers
to load data for. However they are not just loaded completely one after another.
Instead, a 3-staged round-robin is implemented. In the first stage, only
I<Now>
data is loaded, i.e. the currently running and next 2-3 programmes. When
this has been completed for all providers, the next stage begins, which loads
I<Near>
data, i.e. all programmes running in the next 12-24 hours. When that was
completed, the final stage loads the outstanding blocks for all providers.
See below for an explanation what this mode is good for.

=item B<Cyclic: Now - All>

This is the same as the previous mode, except that the
I<Near> stage is skipped.

=item B<Cyclic: Near - All>

This is the same as the mode before the previous one, except that the
I<Now> stage is skipped.

=back

Which mode is best for you depends on how you use the browser. As said
above, if you're mainly using a single provider, stick with the Follow-UI
mode. If you use a merged database, data is automatically loaded for all
contained providers. However if you switch manually between multiple
providers, you should choose one of the manual acquisition modes.

The Cyclic modes enables you to optimize startup time. While in standard
manual mode, the first database is loaded completely before the next one
is started, in Cyclic modes you can specify to load only Now data of all
providers first. Hence already after a couple minutes you'll have updated
Now information for all providers. If you require more look-ahead than
the next 2-3 programmes, e.g. the complete evening, use a Cyclic mode
that starts with the Near stage.

If you use manual acquisition together with a merged browser database,
make sure to put the same provider at top in both lists, i.e. acquisition
should always start for the "master database" of the merge.

Please note that the time until all databases are complete is longer
in the cyclic modes than in standard manual mode. In general, the time
used for the Now and Next stages just adds to the time to complete the
database.

Also note that the cyclic modes depend on the transmission cycles of
the providers. Firstly this means that the time ranges covered by the
cycle stages may differ between providers. Secondly, the cycle times
may vary. In the worst case the Near cycle runs as long as the cycle
for the complete database (e.g. the German provider RTL2). In this case
you don't win anything by selecting a mode that contains a Near stage.



=head1 STATISTICS

You can monitor the progress of acquisition with the timescale windows
which can be opened from the Control menu. There's one window for
the browser database, and one for the acquisition database, if it's
a different one. The timescale windows have one scale for each
network covered by the selected provider. Each scale covers the
next 5 days, starting with the current time. Ranges that are covered
by programmes in the database are marked in red or blue, uncovered
ranges are left black.

The different colors reflect the I<stream> in which the data was received,
or an error status. Stream numbers are directly connected with the cycle
phases mentioned in L<"ACQUISITION MODES">; besides this the difference
is not relevant during normal operation.

=over 4

=item B<red:>

PI blocks received in stream 1, i.e. cycle phase 'Near'.

=item B<blue:>

PI blocks received in stream 2, i.e. cycle phase 'All'.

=item B<shaded red or blue:>

PI blocks from an earlier database version.

=item B<yellow:>

expired or invalid PI blocks (overlapping or zero run-time,
block number not in the range given in inventory, etc.)

=back

In front of the scales there are 5 separate boxes, which refer to the
first 5 programmes (PI blocks) in the inventory (AI block). Please note
that in contrary to the timescales these boxes do not start with the
currently running programmes. They have two purposes: firstly, during
acquisition you can see when the 'Now' cycle phase is complete; secondly
you can check if the data from the Now cycle is expired (marked yellow).
If all 5 are yellow, it's time to update the database.


There are also statistics windows available from the Control menu
which inform you about the browser database and the acquisition progress.
The acquisition statistics are updated every time a new AI block is
received and reset when the database version changes.

The diagram at the left displays a history of fill percentages for
stream 1 and 2; the meaning of the colors is the same as in the
timescale windows.  The baud rates are computed as avarage of received
bits during the total acquisition runtime; every teletext packet is
counted as 45 * 8 Bits.
I<AI min/avg/max>
describes the frequency of AI packet reception as: minimum, average
and maximum interval length between AI blocks. The last 3 lines
reflect the PI (programme information) block counts in the database.

I<Block count db>
gives the total number of PI blocks; in the brackets the sum is broken up
into stream 1, stream 2 and expired & obsolete (colors red, blue and
yellow in the graphics).  The next line has the same meaning, but only
PI blocks of the current database version are counted. 
The last line gives the number of PI blocks that are transmitted in
the current Nextview cycle. This value is computed from the block ranges
given in the AI block. The percentages behind the total express how many
of the blocks already are available in the database; the second of the
percentages only considers PI of the current version.

When you interpret those values, please remember that PI blocks may be
appended to the transmission cycle when programmes have expired (in a
slight violation of the Nextview standard this is done even without
changing the database version). So you might see from time to time that
the fill percentages take a step back down during acquisition. Also note
that expired PI are not accessible from the user interface, however they
are included in the database dump from the I<Control> menu.



=head1 MERGED DATABASES

If you compare databases of different Nextview providers, you will
often find that each has one or more nice features, or covers networks,
that the others lack. Instead of changing back and forth between
several providers all the time, database merging enables to select and
combine features or networks from several original databases into one
newly created database.

When you select the B<Merge providers...> entry from the B<Configure>
menu, you will get a dialog with two listboxes: the left one contains
a list of all currently available databases. The right one is the list
of databases you want to merge. You can add, delete or reorder the
entries is this list. When you're done with your selection, press B<Ok>
to start the merge and switch the browser to the new database.

By ordering providers in your selection, you assign priorities which are
important for conflict resolution. A conflict occurs when programme start
and stop times differ between providers. The likelyhood of such conflicts
depends on the quality of your providers; theoretically they should never
happen except if there are late program changes. In reality, conflicts are
not that unlikely, particularily for programmes early in the morning.
You should put the most reliable provider in the first position, because
conflicting programmes from providers further down will be rejected,
i.e. not added to the merged database.

The B<Configure> button in the dialog gives you fine-control over the
priority of providers during the merge of all distinct programme
attributes. You can even completely remove a provider for an attribute,
e.g. if they transmit false data (e.g. the Sound attribute is handled
wrong by the German provider 3Sat: they have swapped Stereo and Surround).
An exception is the title, where you must not delete any providers.

Attributes that cannot be merged, e.g. editorial rating, are fetched from
the first database in the list that contains the attribute for a given
programme.  An exception are sorting criteria and series, where only the
first provider in the list is queried (i.e. even if the first provider
does not have a sorting criterion for a given programme, the further
databases are not searched) because these types of attributes cannot
be mixed between providers (see also L<"FILTERING">).

Note: If you use a manual or cyclic acquisition mode, you should take care
to include all providers of your merged database in the same order. Else,
program changes will not appear in your database until the provider with
highest priority is loaded. If you stay with the default B<Follow-UI>,
acquisition control will automatically cycle across all merged providers
in the correct order.



=head1 NAVIGATE

The Navigate menu contains a tree of filtering options, that's transmitted
by the selected provider together with the programme data. Filtering enables
to restrict the listing of programme information to those titles matching
the selected menu entry.

The extent and content of this menu depends entirely on the provider.
Unfortunately most providers supply only a very limited menu, so you'll
probably want to define your own filters, as described in the next two
chapters.

Any filter selection can always be undone by the
I<Reset> menu entry or the reset button in the main window.



=head1 FILTERING

Similar to I<Navigate>,
this menu enables to control which of the programmes in the database
are presented in the listing.  However here, you are not limited to a
preselection of filter options.  There's a filter for every kind of
attributes that can be attached to a program, e.g. it's network,
start time, theme descriptors, ... and many more.

Filters can be undone either singularily by selecting the same filter
menu entry again, or globally by clicking on the I<Reset>
button or menu entries.

You can combine as many filters as you want to build a complex filter.
If you combine two filters of different types, only programmes that
match both attributes will be listed (logical AND). If you choose more
than one filter of the same type, all programmes that match either
attribute will be listed (logical OR).

I<Examples:>
If you want to see all programmes listed for either network ARD or
ZDF, simply select both networks. If you want to see all movies
scheduled on PRO7, select network=PRO7 and theme=movies.

Summary of filter options:


=over 4

=item B<Features>

Restrict the listing to programmes that match all given attributes
(logical AND), i.e. sound format, picture format, analog/digital,
encrypted yes/no, live/new/repeat and subtitles yes/no. If you want
to allow more than one value of the same attribute (e.g. picture format
wide OR Pal+) you have to put them into different feature classes.


=item B<Parental Rating>

Restrict the listing to programmes that are suitable for children
of the given age or elder.


=item B<Editorial Rating>

Restrict the listing to programmes that are rated (by the content
provider) to have at least the given quality. The range of rating
values is 1 to 7. Note that some providers do not use all values,
e.g. only 1 to 5, or e.g. just 3, 5 and 7.


=item B<Themes>

Restrict the listing to programmes that have any of the given theme
categories attached to them (logical OR). The Nextview standard
contains a list of 76 predefined themes, which are structured into
11 main categories and subcategories. A programme can have up to
5 themes attached. If you want to restrict the listing to programmes
that have more than one of the given themes (logical AND) you need
to specify them in different theme classes.


=item B<Series>

Restrict the listing to programmes that belong to any of the given
series. A series code always implies a network specification (even if the
same programme is transmitted on different networks). This filter type is
only available for providers that assign series codes; for the other ones
you can use text search among programme titles.


=item B<Program index>

Restrict the listing to programmes who's index is in the given range.
The currently running programme of each network is given index zero,
the following programme of each network index one etc. The three most
important combinations are available as radio buttons:
I<now> (range 0-0),
I<next> (range 1-1) and
I<now or next> (range 0-1).


=item B<Networks>

Restrict the listing to programmes of the given networks. Note that the
order and selection of networks can be configured (see L<"CONFIGURATION">).


=item B<Text search>

Restrict the listing to programmes who's title or description contain
the given text.


=item B<Start Time>

Restrict the listing to programmes who's start time lies in the given
interval. There are two special modes for the interval specification:
If you enable I<Start at current time>
the interval start is fixed to the actual time when the filter is
applied and the value given as stop time is interpreted as duration, i.e.
it's added to the interval start. If you enable I<Stop at end of day>
the interval end is fixed to 23:59 of the same day.


=item B<Sorting Criterions>

Restrict the listing to programmes that have any of the given sorting
criteria attached to them. Sorting criteria work very much like themes,
however their meaning is not predefined by the Nextview standard.
The content provider can use arbitrary numbers to represent an attribute.
Attributes usually are themes that are not in the predefined catalog,
e.g. current events like the Olympic Games, but could also be not
content related at all.  The meaning of these numbers is only
defined by the provider's navigation menus (see L<"NAVIGATE">).

=back


Note that the interpretation of two filter types depends on the
provider: sorting criterion and series. That's because those are
just arbitrary numbers which only have a meaning in the context of
the provider's navigation menu.

I<Hint:>
the filter menu can also be used to examine the filter options
that are invoked by the entries in the Navigate menu.



=head1 FILTER SHORTCUTS

There's a number of predefined filter options in the main window below
the clock. These shortcuts enable you to invoke filters by a single click
of the mouse. You can freely add or remove entries from this list.

When you want to add a shortcut, either choose an entry from the
Navigate menu or define your own filters via the Filter menu, possibly
based on one or more already defined shortcuts. When you have found an
interesting selection, call I<Add filter shortcut...> from the Filter
menu. You'll find a new shortcut appended to the list of existing
shortcuts. First you'll probably want to enter a description in the
entry field at the top of the dialog; default is just "shortcut #xx".
When you're done just press I<Save>, or I<Abort> if you've changed
your mind and don't want to add this shortcut after all.

You can also change descriptions or ordering of existing shortcuts
in this dialog.  If you want to modify the shortcut list without adding
a new one, you can also access the dialog from the I<Configure> menu.

If you want to change the filter settings of an existing shortcut,
then invoke the shortcut, modify the settings as you need and then
use the I<Update filter shortcut> dialog in the Filter menu to save
the new settings of any existing shortcut. You can use the
I<Update & Edit> Button to jump to the filter configuration dialog,
e.g. if you want to fine-tune the description or ordering.

When you deselect a shortcut, either by selecting another shortcut
or clicking on it a second time with I<CTRL> held down, all it's
filters will automatically be undone. Hence when you have two themes
shortcuts, e.g. "Movies" and "Sports", and select first Movies, then
Sports, you'll see only sports programmes afterwards.  However if you
had selected theme movies manually, e.g. by the context menu explained
in the next chapter, the movies filter might remain set, so that you'd
get all programmes of theme movies OR sports.  Since that is usually
not what one expects, a filter mask has been introduced to the shortcut
setting.

The filter mask is defined in the shortcuts dialog with a checkbutton
for each filter type. By default, the mask is enabled for every filter
type you've included in the shortcut filter setting.  When you invoke
the shortcut from the main window later, all filters of the given types
will be cleared (masked out) before the shortcut filters are added.
To return to the above example: if the "Sports" shortcut is defined
with a themes mask, the manually set movies filter would be cleared
before the theme filter is set to sports.

The masking can also be enabled when no filter of that type has been
chosen. This can be used to define I<undo> shortcuts. E.g. choose the
mask 'Themes' if you want a shortcut that allows to clear all
theme-related filters at once. Or enabled all masks for a I<Reset>
button (the only difference to the pre-defined Reset button would
be that the cursor does not jump to the first Now programme.)

You can invoke several shortcuts in parallel by pressing the I<CTRL>
or I<SHIFT> keys when selecting in the listbox - just as you know it
from other applications. However the behavior of the combined shortcuts
is slightly subtle and might not always match your expectations.
That's because the shortcuts are not cleanly separated when processed.
Instead all filters of all selected shortcuts are thrown together and
then processed as if they belonged all to one shortcut in the way
described in L<"FILTERING">. This might change in the future
if someone convices me there's a real need to.



=head1 CONTEXT MENU

Another quick way to select and deselect filters is by using the
context menu, which is popped up with the right mouse button in
the browser window.

This menu consists of two parts: the first entries allow to undo the
previously selected filters - either one by one or globally (reset).

The second part offers a number of possible new filter options, which
depend on the currently selected title and the already selected filters.
The offered filter types include: themes and network of the selected
programme title, it's series code, repeat or original transmission
suppression (only in cunjunction with series or title text filters)
and last but not least the title text (as substring search).

The series and title text filters enable you to check very quickly for
repeats of any programmes. If there is no match for these filters except
for the already selected title, they are not offered.



=head1 CONTROL

Summary of commands available from the Control menu:


=over 4

=item B<Enable acquisition>

Toggles acquisition on or off. Switching off allows other applications
(e.g. a teletext decoder) to use the TV card while you browse the database.
If you have more than one card, it's always possible to use one for
watching TV and the other for loading data.
UNIX: When acquisition is switched off, the I</dev/vbi>
device is freed.  Acquisition can also been turned off automatically
by sending the process the signal HUP.  The process id is stored in
F</tmp/.vbi.pid> while the device is in use.
Windows: When acquisition is switched off, the driver is unloaded.


=item B<Dump stream>

UNIX only: All incoming Nextview blocks are dumped to I<stdout>
in an ASCII format. This is mainly intended for developers, but
it may also help to debug reception problems, because in the dump
you'll find any block that could be decoded without hamming errors,
even before an inventory block (AI) has been received. This may help
if you have very bad reception, because it may take a long time
until a error-free copy of the usually large AI block is received.


=item B<Dump database>

Allows to dump all blocks of selected types in the database to
I<stdout> (UNIX only) or into the given file.  Also intended for
developers mainly.


=item B<View timescales>

Toggles the timescale window for the browser database. The window
reflects for each network included in the selected database, which
time ranges are covered by programme information. If acquisition
is working on the database, you can watch how more and more of the
scales get covered.  See L<"STATISTICS"> for details.


=item B<View statistics>

Toggles the browser database statistics window, which informs you about
number of program entries in the database, fill percentage, expiration
percentage, date of last update etc.  If the acquisition is working on
the same database, it also contains information about state and progress
of acquisition.  See L<"STATISTICS"> for details.


=item B<View acq timescales>

Toggles the timescale window for the acquisition database. This entry
is only available if the acquisition uses a different database than
the browser.


=item B<View acq statistics>

Toggles the acquisition statistics window, which informs you about
state and progress of acquisition. If the acquisition control mechanism
switches to a different database, the acq statistics window will
automatically follow.  See L<"DATA ACQUISITION"> for details.


=item B<Quit>

Close all windows and terminate the application.

=back



=head1 CONFIGURATION

Summary of commands available from the Configure menu:


=over 4

=item B<Select provider...>

Open the provider selection dialog.  This dialog lists all TV channels
from which Nextview data can be received.  When you select a channel
name on the list, you'll see the name of the Nextview service that's
transmitted there and a list of all networks covered by it on the right.
If you leave the dialog with Ok, the selected provider's database will be
loaded into the browser.  The according TV channel will also be tuned
to update the database, if you have selected "Follow-UI" acquisition mode.


=item B<Merge providers...>

Open a dialog that allows to merge several databases into one.
See L<"MERGED DATABASES"> for details.


=item B<Acquisition mode...>

Open a dialog that allows to control the background acquisition process.
See L<"ACQUISITION MODES"> for more details.


=item B<Provider scan...>

Open a dialog that allows to start a scan across all TV channels for
Nextview transmissions.  You should perform this search at least once,
firstly to find out which providers are available in your area, and
secondly to determine the frequencies of all provider's TV channels. They
are required for most acquisition modes, and due to driver limitations
often not available without a scan (e.g. on Windows or Linux with bttv
driver <= 0.7.50). See also L<"GETTING STARTED">.

Check the I<Slow> button if you have bad reception on some channels.
In slow mode the scanner will wait at least for 2 seconds on each
channel for a VPS or PDC identification or an EPG package. Else
channels without a stable video signal and without any teletext packets
will be skipped after 150 ms.

UNIX only: The I<Use .xawtv> button is automatically checked if an xawtv
configuration file is found in your home directory. Instead of searching
all possible channels in all bands, nxtvepg then just checks the channels
assigned there (fine-tuning and absolute frequencies currently are ignored
though).

Use the I<Refresh only> mode if you deleted your database files or if you
upgrade from an incompatible software version. In this mode only the
channels on which Nextview data was received before are checked (the
requencies are kept in the rc/ini file). This enables you to regain your
complete provider list very quickly.


=item B<TV card input...>

Open a dialog where the driver for the TV card can be configured.
On Windows systems you must at least specify which type of tuner
is on your card, and how the PLL needs to be initialized. You can
check your setting by starting an EPG scan: if nothing is found,
try a different setting (or check the antenna cable). For more
details see L<"GETTING STARTED">, or F<README> if you get error messages
from the Bt8x8 driver. If you experience data loss due to heavy
system load, you can raise the acquisition thread priority.

The remaining three configuration options apply to both Linux and
Windows: firstly you may choose which video input source to use.
See L<"DATA ACQUISITION"> about the consequences of not using the
TV tuner as input. If you live in France, select the French
frequency table to be used for the EPG scan.
If you have more than one TV tuner card, you can also choose which
one to use, just like with the B<-card> command line option.


=item B<Xawtv connection...>

Opens a dialog that allows to configure the interaction between the
I<xawtv> TV application and nxtvepg. This menu entry is available
only on UNIX when a F<.xawtv> configuration file is found in your home.
The first three buttons allow to switch the interaction features
separately on or off. If you want to improve startup time, turn them
all off; in this case nxtvepg does not need to search for the xawtv
window (which can take up to several seconds if you have many
applications running or a slow connection to your X server.)
By default all three interaction features are enabled.

The first button relates to the I<Tune TV> button and it's little
popup menu (accessed with right mouse button) below the clock.
If you're not interested in remote-controlling xawtv, switch it off.

If you leave the I<Cursor follows channel changes> option enabled,
nxtvepg will monitor xawtv channel changes. Whenever such a change is
detected, the cursor in the programme listbox will be set onto the
title currently running on that network. During EPG acquisition VPS/PDC
is used to exactly determine the current programme (only on networks
which support VPS/PDC); however if the nominal running time is in the
past it's currently not possible to display the programme in the
listbox. This info may however be sent to xawtv (see next option).
If you have a network filter enabled, it will be switched to the new
network so that you'll get a complete listing of that network's
programmes starting with the currently running one. If you have other
filters than network enabled and they do not cover the current programme
on the new network, the cursor or listbox content will not change.

If you leave the I<Display EPG info in xawtv> option enabled,
nxtvepg will monitor xawtv channel changes. During EPG acquisition
VPS/PDC are also monitored to determine newly starting programmes.
VPS/PDC also allows to detect channel changes on an external input
source, e.g. a satellite receiver connected via the Composite socket.
After a change of channel or current programme title, the info about
the currently running title will be displayed in xawtv. The display
format is selected by the following radio buttons:

With I<Separate popup> nxtvepg will generate a small popup window and
put it right beneath the xawtv window. The blue area in the small bar
on top represents how much of the (nominal) running time lies in the past.
With I<Video overlay> the info will be handed to xawtv and displayed
as subtitles (please note that this option only works properly with
XFree86 version 4 and the XVideo extension). If you prefer a proportional
font add the following line to F<~/.Xdefaults>:

  xawtv.vtx.label.font: -*-helvetica-bold-r-*--14-*-*-*-*-*-iso8859-*

and execute F<xrdb -load ~/.Xdefaults> afterwards. Note that this will
affect subtitles too. Future versions of xawtv will hopefully allow for
dynamic font selection.
I<Video overlay, 2 lines> is the same except that it writes running time
and title in separate lines and additionally contains the percentage of
expired running time. (Not recommended with xawtv versions older than 3.48
as there was a bug in displaying lines of different width.)
With I<Xawtv window title> the info will be sent to xawtv and displayed
in the window title. Except for this last option, you can configure the
desired display duration with the slider at the bottom of the dialog.
A duration of zero means the display will never be removed.


=item B<Select columns...>

Open the browser listbox column configuration dialog. It allows to
select which attributes are displayed for the listed programmes. In the
listbox on the left you find a list of all available categories, e.g.
title, running time & date, TV network, rating, sound and picture format,
i.e. mostly the same attributes that are available for filtering.
The listbox on the right contains the types currently selected for display.
The topmost entry appears on the left side of the listbox.  Press I<Apply>
to refresh the browser listbox with the new column selection and save the
new configuration to the config file.


=item B<Select networks...>

Open the network selection dialog. It allows to permanently suppress
TV networks in a provider's listing, e.g. if you can not receive the
channel. You can also change the order of the networks, e.g. to put
your favorite networks at the top of the filter menus.

This window has two lists: on the left you'll find all networks that are
covered by the provider in their original order, on the right those that
are selected for the programme listing in your preferred order. By default,
both lists will have exactly the same content. If you want to exclude
networks, select them in the right list and press I<Delete>. You can always
include them again by selecting them in the left list and pressing I<Add>.
You can change the order in the right list by selecting one or more networks
and pressing the I<up> or I<down> arrows. If you want the same selection and
order for all providers, you can simply copy your selection with the I<copy>
menu.


=item B<Network names...>

Open the network names configuration dialog. It's main purpose is to
synchronize the network names with I<xawtv> (UNIX TV application), i.e.
the F<~/.xawtv> configuration file. This is required because the network
name is used in communication with I<xawtv> for the I<"Tune TV"> remote
control, and as well for channel change notifications.  For many
networks there will be no need to change anything, but for some there
exist different variants, e.g. in Germany "Super RTL" vs. "S-RTL"
or "KiKa" vs. "Kinderkanal".

Another use of this dialog is to make network naming consistent across
all providers. The names you specify here will be used in the programme
listbox and all filter menus, independently of the provider.

On the left side of the window you'll find a list of all networks of
all known Nextview providers. The names used here are the ones you
configured before, or if you haven't done so, the names that match
the station names in F<.xawtv> best; unmatched names are marked red.
If that file does not exist, the name is taken from the first database
which covers this network, in order of your provider selection history.

On the right side, you're offered four ways to change the name: topmost
is a simple entry field where you can type in an arbitrary name. Below
is a popup menu which contains all network names defined in F<.xawtv>.
Below is a button which contains the one name in F<.xawtv> which resembles
the current string in the entry field most, or I<none>. It's marked red
until it's identical to the entry field. You can copy the name to the
entry field by clicking the button. Below is a listbox with the original
names used in the various provider databases. When you select a name from
the menu or the listbox, it will be copied into the entry field and the
network name list on the left. If you want to save the changed list,
leave the dialog with I<Save>, else use I<Abort>.

Note: if you receive channels that carry multiple networks, e.g.
in Germany "Arte / Kinderkanal", it's recommended to include all
networks' names in the xawtv network name, separated by a slash.
The slash is recognized as separator by nxtvepg (and hopefully future
versions of xawtv) and all resulting segments can be used as
network names.


=item B<Filter shortcuts...>

Open the filter shortcut dialog to rename, reorder or delete shortcuts. 
You have to press the I<Update> button to save any changes for a shortcut
and then close the dialog with I<Save>.
See L<"FILTER SHORTCUTS"> for more details.


=item B<Show shortcuts>

Toggle visibility of the shortcut listbox.


=item B<Show networks>

Toggle visibility of the network filter listbox.


=item B<Show status line>

Toggle visibility of the status line at the bottom of the browser window.


=item B<Show column headers>

Toggle visibility of the browser listbox column header menu bar.


=back



=head1 FILES

=head2 Files used on UNIX systems

=over 4

=item B<~/.nxtvepgrc>

Configuration file where all personal settings are stored. Per default
this is created in your home directory, but a different path and file
name can be specified with the B<-rcfile> option.


=item B</usr/tmp/nxtvdb/nxtvdb-####>

Directory containing one file for each provider's database.
Can be changed with the B<-dbdir> command line option.
The last 4 digits of the file names are the hexadecimal CNI (Country
and Network Identifier) of the provider.


=item B</dev/vbi0>, B</dev/vbi1>, etc.

Device files from which Nextview data is being read during acquisition.
The index postfix can be specified with the B<-card> command line option.


=item B</dev/video0>, B</dev/video1>, etc.

Device files which are needed to set input source (e.g. TV tuner or one of
the composite or S-Video sockets) and tuner frequency for VBI reception,
unless you choose the passive acquisition mode. The index postfix can be
specified with the B<-card> command line option.

The device is only kept open during a provider search. Else, it's just
opened shortly to set the input source and tuner frequency. If the device
is busy (e.g. while you watch TV), acquisition starts on the currently
selected channel and automatically follows any externally controlled
changes (this will be reported, e.g. in the status line at the bottom
of the browser window, as I<forced passive> acquisition mode).


=item B</tmp/.vbi0.pid>, B</tmp/.vbi1.pid>, etc.

This file contains the process id of the Nextview decoder (or the
acquisition slave process) whenever a vbi device is kept open. The
process can be forced to free the device by sending it signal SIGHUP,
e.g. from a wrapper script around a teletext decoder.

=item B<$HOME/.xawtv>, etc.

This file belongs to the TV viewer F<xawtv>. It's not required or
created by nxtvepg. But if it exists, it will be used in the
EPG scan (for a fast scan mode where only the channels defined in
this file will be checked) and in the network name configuration
dialog.

=back


=head2 Files used on Windows systems

=over 4

=item B<nxtvepg.ini>

Configuration file where all personal settings are stored. Per default
this is created in the working directory, but a different path and file
name can be specified with the B<-rcfile> option.


=item B<nxtv####.epg>

One file for each provider's database is created in the working directory
or the one given with the B<-dbdir> command line option.
The last 4 digits of the file base names are the hexadecimal CNI (Country
and Network Identifier) of the provider.

=back


=head1 SEE ALSO

For in-depth information about Nextview please refer to the specifications
ETS 300 707 (data structures and basic principles), ETS 300 708
(transmission protocol) and ETR 288 (code of practice). These specs
are available from http://www.etsi.org/

You can also have Nextview directly inside your television set - check
out the catalogues of Grundig, Loewe, Metz, Sony, Philips, Thompson or
Telefunken. However be aware that not all models do support the same
set of Nextview features.



=head1 KNOWN BUGS

Under Windows there's a risk of system crash ("blue screen") when the
application is terminated by force, e.g. with TerminateProcess(). This
cannot be changed because in this case there's no chance to stop the
driver and disable the interrupt. In normal operation this should be
very unlikely though, since all software exceptions (e.g. page faults)
and shutdown messages are caught and the driver then stopped before
the exit.


=head1 REPORTING BUGS

Feel free to mail any bug reports to me, but please make sure that
(a) you have the latest version of this software, (b) it's not already
in the TODO file and (c) it's not just an error in your provider's EPG
transmission. And please note that I've got no telepathic capabilities,
so be comprehensive in describing your problem. See the README file
for instructions on which information must be included in a bug report.

=head1 AUTHOR

Tom Zoerner, Erlangen, Germany.

Email: tomzo (at) nefkom (dot) net

Many thanks to Mario Kemper for the NetBSD port and beta testing;
to "Mario's brother" for beta testing the Windows port;
to Gerd Knorr for xawtv;
to Ralph Metzler for his teletext decoder;
to Edgar Toernig for the Latin-1 conversion tables in alevt;
and last but not least to the authors of bttv and v4l for their excellent work.

=head1 COPYRIGHT

Copyright (C) 1999, 2000, 2001 by Tom Zoerner.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License Version 2 as
published by the Free Software Foundation, e.g. at
http://www.fsf.org/

This program is distributed in the hope that it will be useful, but
B<WITHOUT ANY WARRANTY>; without even the implied warranty of
merchantability or fitness for a particular purpose. See the
file F<COPYRIGHT> for more details.

